spring:
  application:
    name: varamy
  mail:
    host: smtp.beget.com   # например, smtp.yandex.ru
    port: 465
    username: katok@katok.pro
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:vara_my_staging}
    username: ${DB_USER:vara}
    password: ${DB_PASSWORD:vara}
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 10MB      # максимальный размер одного файла
      max-request-size: 10MB   # общий размер всего запроса (включая другие поля)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect   # 👈 теперь внутри hibernate
        temp:
          use_jdbc_metadata_defaults: false
        metadata:
          cache:
            enabled: false
        jdbc:
          batch_size: 20
          lob:
            non_contextual_creation: true
        format_sql: true
    show-sql: false

  flyway:
    enabled: false

server:
  port: ${SERVER_PORT:8082}
  forward-headers-strategy: framework  # Важно для работы за прокси
  error:
    include-message: always
    include-binding-errors: always

jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationMustBeAtLeast32CharactersLong}
  access-token-expiration: 604800000   # 7 дней (7 * 24 * 60 * 60 * 1000)
  refresh-token-expiration: 604800000 # 7 дней

logging:
  level:
    info.prorabka.varamy: DEBUG
    info.prorabka.varamy.config: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging.simp: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.transaction: DEBUG
    com.google.firebase: DEBUG

file:
  upload-dir: \uploads   # абсолютный путь на сервере

sms:
  gateway:
    enabled: true   # должно быть true
    user-id: "a42abfcf-8f42-4dac-8f6d-95e8c8d756da"  # ID пользователя SMS_GATEWAY
  mock-mode: false
  provider:
    enabled: false
    # включаем HTTP-провайдера
    url: https://sms.ru/sms/send
    api_id: "1E60E0CB-37D0-39A2-4073-8EF4C36D55D1"         # защищённая переменная окружения
    sender: "katok.pro"        # опционально

huawei:
  push:
    app-id: 118382697
    client-secret: d98c465711b362a315ca3d3b15bdcaec93e1342d93cc46ab4073ea012ba58de7
    client-id: 118382697
    token-url: https://oauth-login.cloud.huawei.com/oauth2/v3/token
    push-url: https://push-api.cloud.huawei.com/v1/${huawei.push.app-id}/messages:send

rustore:
  push:
    api-key: SvzKG7oosMgH2QlY9OE6yne2WyvXmnQ0dPwIIxup8UIW4KgNFeM9TPgUEJtkYchM
    project-id: jl4uTL62lrP4Kx3GlhMfSMi7y6f6eY0d
    url: https://push-cloud.vk.com/api/v1/messages

verification:
  code:
    expiry-minutes: 5  # Время жизни кода подтверждения (минут)

app:
  cors:
    allowed-origins:
      - "http://katok.pro"
      - "https://katok.pro"
      - "http://www.katok.pro"
      - "https://www.katok.pro"
      - "http://soberi.info"
      - "https://soberi.info"
      - "http://www.soberi.info"
      - "https://www.soberi.info"
      - "http://localhost:5500"
      - "http://127.0.0.1:5500"
      - "http://192.168.0.70:8081"
      - "http://92.125.255.63:8081"
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - PATCH
    allowed-headers:
      - "*"
    exposed-headers:
      - Authorization
      - Content-Type
    allow-credentials: true
    max-age: 3600
    cleanup:
      archive-months: 5  # Количество месяцев хранения архивных объявлений
      archive-cron: "0 0 3 * * ?"  # Ежедневно в 3 часа ночи
  base-url: https://varamy.online/api   # внешний URL с префиксом /api2

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    try-it-out-enabled: true
    persist-authorization: true
    disable-swagger-default-url: true
  packages-to-scan: info.prorabka.varamy.controller
  paths-to-match: /**

debug: true